### ISSUE TITLE
The script won't read any file with a space

### ISSUE THREAD

**Issue by JustKato** [MissingPotato/UltimateCompressor#1]
The `ls` command displays all the files, then the grep filters them for what we can use, but when we loop through them, spaces cut the file basically making it as if `this file.png` is 2 files not 1

**Comment by lbonanomi** [comment]
Hi @MissingPotato! I think bash is tokenizing your input.

`files=$(ls "$input_dir" | grep "[jJ][pP][gG]";);` treats every whitespace seperated "word" as a file name even though files names can have spaces in them. 

You could try restructuring 

```bash
files=$(ls "$input_dir" | grep "[pP][nN][gG]";);
printf "\n${COLOR_BLUE}Processing PNG files...${COLOR_GREEN}";
for filename in $files; do
```

With something like:

```bash
printf "\n${COLOR_BLUE}Processing PNG files...${COLOR_GREEN}";
ls "$input_dir" | grep "[pP][nN][gG]" | while read filename; do
```

Using `read` will make bash read line-by-line instead of word-by-word.
